### ISSUE TITLE
Remote profile updates in SFA works not reliably

### ISSUE THREAD

**Issue by Danstiv** [SagerNet/sing-box#3409]
### Operating system

Android

### System version

Android 15

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.12.8

### Version

```shell

```

### Description

Hello!
It seems that app does not update remote profiles when SFA is active.
Sometimes updates occur in time, sometimes with a delay of several hours, sometimes the profile may not be updated for several days.
I tried to describe a reliable way to reproduce the problem, but I'm not sure that it will work 100%.

### Reproduction

1. Create some minimal config, empty json object is enough: `{}`
2. Put the created config in the https accessible directory.
3. Clear SFA app data.
4. Create remote profile in the SFA, enter url that points to the previously created config.
5. Enable autoupdate and set update interval to 15 minutes.
6. Start the SFA.
7. Wait 30-40 minutes and check profile last update time.

### Expected behavior
Update time should be not more than 15 minutes in the passed.

### Actual behavior
Update time is equal to profile creation time.
Checking the http server logs also showed that SFA requested config only once, during profile creation.

### Logs

```shell

```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [x] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [x] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [x] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [x] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by ilfat12** [comment]
I have the same issue. I manually updated the remote config yesterday after modifying it, and it still hasn’t updated even once, although it is set to update every 60 minutes.
On the tablet, the version is 1.11, and there the config updates regularly.

**Comment by Danstiv** [comment]
Finally, I seem to have found the cause.
When we first install and launch the app, the `reconfigureUpdater function` is called.
This function discovers that there is no remote profiles, and does not register the background task for updating, this is right, and it should be.
However, after we add the profile, no one calls `reconfigureUpdater`, and as a result, the profile is never updated.
@ilfat12, could you try checking that Theory?
To do this, you need to force close the app, then launch it and check profile last update date.
It is also worth continuing to use the application as usual, from time to time checking the last date of update, and now the profile should be updated with configured frequency as expected.

**Comment by ilfat12** [comment]
> could you try checking that Theory?

Yesterday I installed version 1.12.0 beta 14, and since yesterday the remote config hadn’t been updating. I manually stopped the sing-box application, and after restarting it, the config updated immediately. After that, it started updating every hour as expected.
So it looks like your theory is correct.

**Comment by Danstiv** [comment]
I think this is a trivial fix, @nekohasekai, can you pay attention to this issue?

**Comment by nekohasekai** [comment]
Could you check if this has been correctly fixed in the latest stable version?

**Comment by Danstiv** [comment]
Not fixed. I imported bpf rather than creating the profile manually, maybe that makes a difference. Anyway, when importing bpf with autoupdate configured, autoupdate not working.
SFA 1.13.19

**Comment by Danstiv** [comment]
Tested STR exactly, the bug described in the issue was fixed, but importing bpf as a first profile reproduces the issue. I can open another issue if needed.
